project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - lpt_etl.qmd
    - parcel_profiles.qmd

website:
  title: "Vegetation Condition"
  favicon: "images/inyo_logo.png"
  navbar:
    title: "Vegetation Condition"
    logo: images/inyo_logo.png
    left:
      - href: lpt_etl.qmd
        text: Data
      - href: index.qmd
        text: Annual Summary
      - href: parcel_profiles.qmd
        text: Parcel Profiles
      - icon: github
        href: https://github.com/inyo-gov/vegetation-condition
    background: dark
    search: true

format:
  html:
    theme: cosmo
    linkcolor: "#2E86AB"
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    page-layout: article
    embed-resources: true
    fig-responsive: true
    fig-dir: figure-html
    subtitle: "Inyo County, California"
    footer: "Â© 2026 Inyo County, California. All rights reserved."

editor: visual
