project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - lpt_etl.qmd
    - parcel_profiles.qmd

website:
  title: "Vegetation Condition"
  favicon: "images/inyo_logo.png"
  navbar:
    left:
      - href: lpt_etl.qmd
        text: Data
      - href: index.qmd
        text: Annual Summary
      - href: parcel_profiles.qmd
        text: Parcel Profiles
      - icon: github
        href: https://github.com/inyo-gov/vegetation-condition

format:
  html:
    theme: sandstone
    linkcolor: blue
    css: styles.css
    toc: true
    embed-resources: true

editor: visual
